### PR TITLE
19.05 Release

### PR DESCRIPTION
**Pull request by cambw**
Lots of little fixes:
- Fix error upon saving EDS config (thanks Alex!)
- Fix eds-methods.pl not being included by Perl (thanks Alex & Nick & Liz!)
- Fix proxy IP access (Thanks Bywater!)
- Fix cart issues (Thanks Alvet & me 😄 !)
- Fix needless warnings (Thanks David!)
- Fix for plugin directory locations (Thanks Kyle!)

Tested and working on my AWS 19.05 dev instance.

Co-Authored-By: @cambw, @kidclamp, @alex-buckley, @alvetm, @minusdavid, @wizzyrea , @kylemhall

Tested By: @cambw, @hayleymapley, @alex-buckley

### CODE REVIEW

**Comment by cambw** [comment]
@alexklbuckley do you have any capacity for testing this update?

**Comment by Alex-Buckley** [comment]
Hi Cam,  my colleague @hayleymapley ( hayleymapley ) said she is happy to test it this afternoon :)

**Comment by cambw** [comment]
Awesome, let me know if there's any issues or anything we can do to make the plugin work on more configurations with less tweaking.

**Comment by hayleymapley** [comment]
Hi @cambw, I ran out of time today but will test early next week! Sorry :)

**Comment by cambw** [comment]
@hayleymapley no prob!

**Comment by hayleymapley** [comment]
Hi @cambw,

Would it be okay to test this release running Koha 18.05? Or do you think it wouldn't work at all

Cheers,
Hayley

**Comment by cambw** [comment]
Hey! Yeah it should work fine. I don’t think there was anything specific to 19.05 that would break 18.05.

________________________________

**Comment by hayleymapley** [comment]
Hi @cambw,

Definitely getting less errors than before, however the plugin still isn't quite working for me.

In the configuration page for the plugin when I click the 'Load setting from EBSCOAdmin Now' button it opens a window which should say 'info stored' but instead takes me to https://sitename.koha.catalystdemo.net.nz/plugin/Koha/Plugin/EDS/opac/eds-raw.pl?q=info and displays a Koha 404 page. 
There is also an error from eds-raw.pl 'Loading failed for the <script> with source “https://sitename.koha.catalystdemo.net.nz/plugin/Koha/Plugin/EDS/js/EDSScript.js'.

Do you have any ideas as to what might be causing this?

Cheers,
Hayley

**Comment by hayleymapley** [comment]
Hi @cambw, Alex has managed to get it further than before (I had missed a line in the config, d'oh!).

Clicking on a records led to an error saying unexpected [% END %] in template in the last line of eds-detail.pl, so we removed it and it printed out all of this Javascript underneath the detail pages of Discovery records: 
var q_array = new Array(); // holds search terms if available function highlightOff() { $("#catalogue_detail_biblio").removeHighlight(); $(".highlight_toggle").toggle(); } function highlightOn() { var x; for (x in q_array) { q_array[x] = q_array[x].replace(/\w*:([\w])/, "$1"); $(".title").highlight(q_array[x]); $(".author").highlight(q_array[x]); $(".results_summary").highlight(q_array[x]); } $(".highlight_toggle").toggle(); } $(document).ready(function() { $('#bibliodescriptions').tabs(); $(".branch-info-tooltip-trigger").tooltip({ position: { my: "left+15 center", at: "right center" }, show: 50, hide: 50, content: function(){ var element = $(this).next("div"); return element.html(); } }); $(".holdingst").dataTable($.extend(true, {}, dataTablesDefaults, { "aoColumns": [ null, null, null, null, { "sType": "title-string" }, ] })); if (arrPagination.length > 0) { renderPagIndexList(pag_index_ini, $("#listResults")); } $("#a_listResults").click(function(e) { if (arrPagination.length > 0) { e.preventDefault(); var navigation = $(".results-pagination"); if (navigation.css("display") == 'none') { navigation.show(); var newtitle = $(this).attr('title').replace('Show', 'Hide') $(this).attr('title',newtitle); renderPagination(pag_index_ini, arrPagination.length - 1, $("#ul_pagination_list"), false); } else { navigation.hide(); var newtitle = $(this).attr('title').replace('Hide', 'Show') $(this).attr('title',newtitle); } } }); $("#close_pagination").click(function(e) { e.preventDefault(); var navigation = $(".results-pagination"); navigation.hide(); }); (function prepareShelfBrowser(){ $(".main").on("click",".close_shelf",function(e){ e.preventDefault(); $("#shelfbrowser").toggle(); }); $(".main").on("click", "#browser_previous a", function(e){ e.preventDefault(); $.ajax({ url: "/cgi-bin/koha/svc/shelfbrowser.pl", type: "POST", data: { "shelfbrowse_itemnumber": $("#browser_previous a").data( "prev-itemnumber" ) }, success: function(data){ $("#shelfbrowser").replaceWith(data); } }); }); $(".main").on("click", "#browser_next a", function(e){ e.preventDefault(); $.ajax({ url: "/cgi-bin/koha/svc/shelfbrowser.pl", type: "POST", data: { "shelfbrowse_itemnumber": $("#browser_next a").data( "next-itemnumber" ) }, success: function(data){ $("#shelfbrowser").replaceWith(data); } }); }); }()); // ----------------------------------------------------- // star-ratings code // ----------------------------------------------------- // hide 'rate' button if javascript enabled $('input[name="rate_button"]').remove(); $(function () { $(".auto-submit-star").rating({ callback: function (value, link) { // if the new value equals the old value, dont execute callback... // just do nothing! if ($("#rating_value").attr("value") != value) { $(function () { $.post("/cgi-bin/koha/opac-ratings-ajax.pl", { rating_old_value: $("#rating_value").attr("value"), borrowernumber: "", biblionumber: "", rating_value: value, auth_error: value }, function (data) { if (data.auth_status != 'ok') { window.alert(_("Your CGI session cookie is not current. Please refresh the page and try again.")); } else { $("#rating_value").val(data.rating_value); if (data.rating_value) { $("#rating_value_text").text(_("your rating: ") + data.rating_value + ", "); } else { $("#rating_value_text").text(''); } $("#rating_text").text(_("average rating: ") + data.rating_avg_int + " (" + data.rating_total + ' ' + _("votes") + ")"); } }, "json"); }); }; } }); }); // ----------------------------------------------------- }); var timeoutRFW; var totalPagItemList = 10; function rewindList() { var ul = $("#listResults"); var li_ini = ul.children(':first').next(); var index_ini = pag_index_ini; if (li_ini) { index_ini = parseInt(li_ini.attr("class").substring(7), 10); } var li_end = ul.children(':last').prev(); var index_end = arrPagination.length - 1; if (li_end) { index_end = parseInt(li_end.attr("class").substring(7), 10); } if (index_ini > pag_index_ini) { renderPagIndexList(index_ini - 1, ul, false); renderPagination(index_ini - 1, arrPagination.length - 1, $("#ul_pagination_list"), true); } }//rewindList function forwardList() { var ul = $("#listResults"); var li_ini = ul.children(':first').next(); var index_ini = pag_index_ini; if (li_ini) { index_ini = parseInt(li_ini.attr("class").substring(7), 10); } var li_end = ul.children(':last').prev(); var index_end = arrPagination.length - 1; if (li_end) { index_end = parseInt(li_end.attr("class").substring(7), 10); } if (index_end < arrPagination.length - 1) { renderPagIndexList(index_ini + 1, ul, false); renderPagination(index_ini + 1, arrPagination.length - 1, $("#ul_pagination_list"), true); } }//forwardList function renderPagIndexList(index, ul) { var $kids = ul.children("li"); if ($kids.length > 0) { $kids.each(function() { $(this).remove(); }); } var li; var html = ""; var ini = index - 1; var end = ini + totalPagItemList - 1; li = $("
"); html = (index > pag_index_ini)?"«":"«"; li.html(html); ul.append(li); var title = ""; for (var i=index; i < arrPagination.length && i < index + totalPagItemList; i++) { if (arrPagination[i] == undefined) continue; var li = $("
"); if (arrPagination[i].url != "") { title = _("See biblio") + " "" + arrPagination[i].title + "" "; if (arrPagination[i].author != "") title += " " + _("by") + """ + arrPagination[i].author + """; title += " " + _("with biblionumber") + " " + arrPagination[i].biblionumber; html = ""; } else html = i; li.html(html); li.attr("class", "li_pag_" + i); ul.append(li); } li = $("
"); ini = index + 1; end = (arrPagination.length > index + totalPagItemList)?index + totalPagItemList:arrPagination.length - 1; html = (end <= arrPagination.length - 1 && (end - index) >= totalPagItemList)?"»":"»"; li.html(html); ul.append(li); }//renderPagIndexList function renderPagination(index, total, ul, highlIndex) { for (var i = pag_index_ini; i <= total; i++) { if (arrPagination[i] == undefined || arrPagination[i].url == "") continue; $("#li_pag_" + i).remove(); } var j = 0; for (var i = index; i <= total && j < totalPagItemList; i++) { if (arrPagination[i] == undefined || arrPagination[i].url == "") continue; var li = $("
"); var html = "" + i + "" + arrPagination[i].title + ""; if (arrPagination[i].author) html += "
by " + arrPagination[i].author; li.html(html); if (highlIndex && i == index) li.css("backgroundColor", "#DDDDDD"); ul.append(li); j++; } for (i = pag_index_ini; i < index && j < totalPagItemList; i++) { if (arrPagination[i] == undefined || arrPagination[i].url == "") continue; $("#li_pag_" + i).remove(); var li = $("
"); var html = "" + i + "" + arrPagination[i].title + ""; if (arrPagination[i].author) html += "
" + _("by") + " " + arrPagination[i].author; li.html(html); ul.append(li); j++; } }//renderPagination //]]> 

When doing a Discovery Search we now get results, but clicking on local records gives an internal server error and shows this in the plack-error.log:

CGI::param called in list context from /var/lib/koha/kinder/plugins/Koha/Plugin/EDS.pm line 123, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 412.

Can't call method "title" on an undefined value at /usr/share/koha/opac/cgi-bin/opac/opac-detail.pl line 459.

Hope this helps!

**Comment by cambw** [comment]
Awesome, thanks @hayleymapley. I did mean to point you towards the wiki that has some instructions around getting Apache to map and execute stuff in the plugin folder, if that was your issue. I've patched the issue that you and Alex found, but didn't update the KPZ. I've just updated the PR with the new file, let me know if that fixes the error!

**Comment by hayleymapley** [comment]
Hi @cambw , 

I downloaded the new kpz file and tested it, and unfortunately I'm still getting:
When doing a Discovery Search we now get results, but clicking on local records gives an internal server error and shows this in the plack-error.log:

CGI::param called in list context from /var/lib/koha/kinder/plugins/Koha/Plugin/EDS.pm line 123, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 412.

Can't call method "title" on an undefined value at /usr/share/koha/opac/cgi-bin/opac/opac-detail.pl line 459.

**Comment by hayleymapley** [comment]
Hi @cambw,

Alex has narrowed down the issue to the resultsid parameter which is in the URL and being passed to the opac-details.pl. When clicking on a local biblio in the Discovery search results page, Koha tries to find a biblio with the resultsid passed through instead of the actual biblionumber e.g. 1 instead of 302798.

Resulting in: Can't call method "title" on an undefined value at /usr/share/koha/opac/cgi-bin/opac/opac-detail.pl line 459.

Hope this helps, let us know if you need more info!

Cheers,
Hayley and Alex

**Comment by cambw** [comment]
@hayleymapley ahhh I see, I won't have a time to fix today. Will find some time next week. 
Could you want to email me (cwu@ebsco.com) the URL + some creds for the testing site you're using? I don't have one with a proper catalogue that's being harvested by EDS.

**Comment by hayleymapley** [comment]
No rush @cambw, email sent :)

**Comment by hayleymapley** [comment]
Hi @cambw, here is what we have done to fix the issue for one of our sites:

In opac-detail.pl find this line (around line 458):

next unless ($arrBiblios[$j]);

replace with:

next unless ($arrBiblios[$j] == $biblionumber); #eds doesn't seem to pass through the @arrBiblios in the right way, it always starts at 1. everything seems to still work here though.

Cheers,
Hayley

**Comment by cth3403** [comment]
Hi,
 
Will it be OK to use this on Koha 18.11? 
We have a site in the UK that are having a problems adding catalogue items to the cart ( issue #66 ). They currently have version 17.11.005 installed. 

Thanks,
Joe

**Comment by cambw** [comment]
Hey @cth3403 ,
Yes plugin will most likely work fine on 18.11
You're welcome to grab the kpz and test!
Thanks!

**Comment by mmabrahamson** [comment]
Hi All!  I'm the new Library Service Engineer at EBSCO that will be keeping up with this plugin.  I'd like to merge the above work from Cam as it seems to be functioning as expected in my personal Koha 19.11 install, and begin additional fixes in a 19.11 release.  

Before I do that though, I'd appreciate any help from you all who are likely much more experienced with Koha in general to let me know if there's any reason not to merge this update and move on to other issues.  Please let me know if you can also test this and verify it's working as intended or else if there are any install breaking bugs you're still seeing that shouldn't be merged.  Thanks in advance and looking forward to working with this community!

**Comment by hayleymapley** [comment]
Hi Michael,
Us in the Koha team @ Catalyst are happy for you to merge this in.
And nice to e-meet you!

**Comment by minusdavid** [comment]
Welcome to the fold, Michael.

I haven't done much with the EDS plugin for a long time, and I doubt that I will for a while, but it's probably all good to merge. If something does come up, if you're responsive to issue reports, I'm sure all will be well.

**Pull request merged**
