### PR TITLE
Fix multi plugindirs

### PR DESCRIPTION
**Pull request by fridobox**
Some places are missing the check that "pluginsdir" may be multi in
config file koha-conf.xml

### CODE REVIEW

**Comment by fridobox** [comment]
Still valid with version 19.05

**Comment by fridobox** [comment]
Oh maybe better fix this with Koha::Plugin->bundle_path()

**Comment by fridobox** [comment]
See https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=26803

**Comment by fridobox** [comment]
To realy fix you should consider changing all perl into modules, using '.pl' scripts to store methods is really strange :
 require $PluginDir.'/admin/setuptool.pl';

You should consider using Object programming in '.pm' modules, with new() and self() to transmit Koha::Plugin object.

**Comment by mmabrahamson** [comment]
Added in PR #90

**Pull request closed without merging**
