### PR TITLE
Cart issues

### PR DESCRIPTION
**Pull request by mmabrahamson**
This resolves issues with the cart not allowing you to remove items, as well as issues with the download and email functionality.

To Test:
Install the kpz.
Confirm that you can add EDS and Catalog items to cart.
Confirm that items can be removed from cart individually.
Confirm that download and send functionality works for your cart.

### CODE REVIEW

**Comment by cambw** [comment]
Will get Cam T to review today

**Comment by CameronThomas-EBSCO** [comment]
> This resolves issues with the cart not allowing you to remove items, as well as issues with the download and email functionality.
> 
> To Test:
> Install the kpz.
> Confirm that you can add EDS and Catalog items to cart.
> Confirm that items can be removed from cart individually.
> Confirm that download and send functionality works for your cart.

**Review by CameronThomas-EBSCO — COMMENTED** [review]
Installed the kpz on my Koha Virtual Machine (no issues).

- Confirmed you can add EDS and Catalog items to the cart (Confirmed on Virtual Machine and internal Koha link).
        **One issue to confirm. If they do have the cart window open and they add another item to the cart, should the cart refresh with the additional item? At this stage it does not refresh**

- Confirmed that you can remove items from the cart individually (Confirmed on Virtual Machine and internal Koha link).

- Confirmed that you can download and the send functionality works for my cart (Confirmed on internal Koha link only).

**Comment by mmabrahamson** [comment]
I don't believe the cart autoupdates normally without the plugin.  Thanks for the review!

**Pull request merged**
